#!/bin/bash

cp /usr/local/etc/minecraft/craftbukkit-1.7.2-R0.3.jar /data/
chmod -x craftbukkit-1.7.2-R0.3.jar

if [ ! -f /data/server.properties ]
then
    cp /usr/local/etc/minecraft/server.properties /data/
fi

exec java -Xmx512M -Xms512M -jar /craftbukkit-1.7.2-R0.3.jar
